# Generated by Django 4.0.5 on 2022-07-14 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_created_producto_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idGenero', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID de Genero')),
                ('nombreGenero', models.CharField(max_length=50, verbose_name='Nombre del género')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('correo', models.CharField(max_length=30, verbose_name='Correo')),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.genero')),
            ],
        ),
    ]
